#######################
### INHERIT CONFIGS ###
#######################

source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/look.conf
source = ~/.config/hypr/rules.conf

################
### MONITORS ###
################

monitor=eDP-1,1920x1080@144,0x0,1
monitor=HDMI-A-1,1920x1080@165,0x-1080,1

#################
### AUTOSTART ###
#################

exec-once = gentoo-pipewire-launcher &
exec-once = waybar
exec-once = dunst
exec-once = fastfetch
exec-once = swww-daemon
exec-once = hypridle
exec-once = unclutter -idle 5

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland
env = QT_QPA_PLATFORMTHEME, kde

env = QT_STYLE_OVERRIDE,kvantum
env = QT_QPA_PLATFORMTHEME,kvantum

#############
### INPUT ###
#############

input {
    kb_layout =us,ru
    kb_variant =
    kb_model =
    kb_options =grp:alt_shift_toggle
    kb_rules =
    follow_mouse = 1
    sensitivity = 0
    
    touchpad {
        natural_scroll = false
    }
}
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
